### PR TITLE
removed dependecies and fixed demo

### PR DESCRIPTION
**Pull request by vbandrade**

### CODE REVIEW

**Comment by pinkfish** [comment]
This does mean it will only display the datetime in the current timezone right?  I guess you could convert everything to the default timezone first.

**Comment by vbandrade** [comment]
I made a mess with github and sent this pr to  your repo instead of mine. sorry.

**Comment by pinkfish** [comment]
Ahh, no worries.  I find github a little confusing around that too :)

You find the tzdatetime a bit hard to work with I take it?

**Comment by vbandrade** [comment]
a bit, yeah.
but in my use case events have the same duration and timezones arent necessary.
I was looking for ways to hook up a list with a calendar picker and this solution was a good start. I'll also remove the banner images.

**Pull request closed without merging**
